name: Публикация новых версий пакетов
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  publish:
    name: Публикация новых версий пакетов
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - uses: docker://quay.csssr.cloud/csssr/github-info:v1
        id: gh

      - uses: actions/checkout@v2
        with:
          ref: refs/heads/${{ steps.gh.outputs.branch }}
          token: ${{ secrets.ADMIN_TOKEN }}


      - name: Скачивание всей git-истории (чтобы работал from-git)
        run: git fetch --prune --unshallow

      - name: Установка ноды
        uses: actions/setup-node@v2.1.1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Установка зависимостей
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Сборка пакетов
        run: yarn build

      - name: Публикация пакетов
        uses: gpn-prototypes/vega-actions/release-lerna-packages@master
        with:
          branch: ${{ steps.gh.outputs.branch }}
          main_branch: master
          gh_user: GitHub Workflow
          gh_email: workflow@github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}


      - name: Генерация CHANGELOG
        id: changelog
        uses: gpn-prototypes/vega-actions/generate-changelog@master
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
        if: "contains(steps.gh.output.branch, 'master')"

      - name: Создание релиза на Github
        uses: gpn-prototypes/vega-actions/generate-gh-release@master
        with:
          changelog: ${{ steps.changelog.outputs.changelog }}
          token: ${{ secrets.ADMIN_TOKEN }}
          main_package: "@gpn-prototypes/vega-ui"
        if: "contains(steps.gh.output.branch, 'master')"

      - name: Обновление CHANGELOG.md
        uses: gpn-prototypes/vega-actions/update-changelog@master
        with:
          changelog: ${{ steps.changelog.outputs.changelog }}
        if: "contains(steps.gh.output.branch, 'master')"

      - name: Commit CHANGELOG.md
        run: |
          git add CHANGELOG.md
          git commit -m "chore(changelog): обновление changelog [skip ci]" --no-verify --quiet
          git push origin master
        if: "contains(steps.gh.output.branch, 'master')"



