name: Добавление описания в Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  update_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: tzkhan/pr-update-action@v2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          lowercase-branch: true
          head-branch-regex: '(vega-\d+)|(dependabot\S+)'
          title-template: ' '
          body-template: |
            ## Задача
            Стенд: http://%headbranch%.vega-ui-storybook.csssr.cloud
            Cсылка в Jira CSSSR на задачу: https://jira.csssr.io/browse/%headbranch%
          body-newline-count: 2
